version: "3.9"

services:
  djangoapp:
    container_name: authorz
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=zerg
      - PG_PASSWORD=zergling
      - PG_DB=prdb
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=prdb
      - POSTGRES_USER=zerg
      - POSTGRES_PASSWORD=zergling
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
