version: "3.9"

services:
  djangoapp:
    container_name: authorz1
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=zerg
      - PG_PASSWORD=zergling
      - PG_DB=prdb
      - PG_PORT=5432
      - PG_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    container_name: db1
    image: postgres:12
    environment:
      - POSTGRES_DB=prdb
      - POSTGRES_USER=zerg
      - POSTGRES_PASSWORD=zergling
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis1
    image: redis:latest
volumes:
  pgdata: {}