# Generated by Django 4.2.7 on 2023-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorz', '0004_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
