# Generated by Django 4.2.7 on 2023-12-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorz', '0006_alter_img_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
