# Generated by Django 4.2.7 on 2024-01-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorz', '0020_alter_f1driver_age_alter_f1driver_championships_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F1Driver',
        ),
    ]
