# Generated by Django 4.2.7 on 2024-01-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorz', '0021_delete_f1driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='owner',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
