# Generated by Django 4.2.7 on 2024-02-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorz', '0027_alter_chatmessage_recipient_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sdescription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
